version: "3.9"
services:
  mongodb:
    image: mongo:4.4.6
    container_name: menu-mongo
    networks:
      - componse-bridge
  
  alurabooks:
    image: aluradocker/alura-book:1.0
    container_name: alurabooks
    networks:
      - compose-bridge
    ports:
      - 3000:3000
    depends_on:
      - mongodb

networks:
  compose-bridge:
    driver: bridge
